### ISSUE TITLE
Clover Critical Mistake

### ISSUE THREAD

**Issue by ginkgo20** [lucametehau/CloverEngine#127]
![Screenshot 2023-06-10 at 21-33-35 Analysis Board - 365Chess com](https://github.com/lucametehau/CloverEngine/assets/132969765/a651e73f-be1d-46d3-931a-770ecb89939f)

**Comment by lucametehau** [comment]
I think you were the critical mistake, consider seeing a doctor. Thanks for contributing with absolutely nothing to the community and annoying SF members!

**Comment by ginkgo20** [comment]
> I think you were the critical mistake, consider seeing a doctor. Thanks for contributing with absolutely nothing to the community and annoying SF members!

Please be nice to me. Can I ask you "which my commit or issue in SF community was mistake"?

> And of course, don't forget to report any possible bugs! ;)

I created a good first issue for Clover but you ignored it. Here is a stronger version of this issue :

- https://github.com/jhonnold/berserk/issues/488

**Comment by lucametehau** [comment]
No need to be nice with you, many community members where already nice enough, whereas you just wanted to troll. You are either a functional analphabet and do not understand what an issue is or you are here just to troll, in both cases your presence here is not welcome and please don't feel like you are helping or accomplishing something. All you are doing is making a fool of yourself, which you already are, a low life that trolls a relatively small community, because their parents don't love them. Have a shit day!

**Comment by ginkgo20** [comment]
I don't talk much with rude person like you. Every second of my life I rise because I have team fearless at my back. Bye!
