### ISSUE TITLE
For Android compatibility 

### ISSUE THREAD

**Issue by Shiv0921** [lucametehau/CloverEngine#67]
Any chance that the source code will become compatible with Android again (arm64-v8a and armeabi-v7a)?

**Comment by lucametehau** [comment]
Hey. I assume by "being compatible with Android again" that you refer to Clover 3.0, which I think worked on Android. The addition of SIMD related stuff is the cause for this. Right now, I don't really know stuff about cross compiling for Android, but I'll study it in the following days and I'll let you know when this issue is fixed.

**Comment by lucametehau** [comment]
I have no way to test this, but since then I have been a bit more careful about SIMD support for different archs. So I will just assume it works, unless reported otherwise.
